name: Booking Automation CI/CD

on:
  push:
    branches: [ staging, alpha, main, production ]
  pull_request:
    branches: [ staging, alpha, main, production ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        environment: [staging, alpha, production]
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    - name: Set up Chrome
      uses: browser-actions/setup-chrome@latest
    
    - name: Set up ChromeDriver
      uses: nanasess/setup-chromedriver@v2
    
    - name: Determine environment from branch
      id: env
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
          echo "environment=staging" >> $GITHUB_OUTPUT
        elif [[ "${{ github.ref }}" == "refs/heads/alpha" ]]; then
          echo "environment=alpha" >> $GITHUB_OUTPUT
        elif [[ "${{ github.ref }}" == "refs/heads/main" ]] || [[ "${{ github.ref }}" == "refs/heads/production" ]]; then
          echo "environment=production" >> $GITHUB_OUTPUT
        else
          echo "environment=staging" >> $GITHUB_OUTPUT
        fi
    
    - name: Run tests
      run: |
        mvn clean test -Denvironment=${{ steps.env.outputs.environment }}
      env:
        MAVEN_OPTS: -Xmx1024m
    
    - name: Generate test report
      if: always()
      run: |
        mvn surefire-report:report-only
        mvn site -DgenerateReports=false
    
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results-${{ steps.env.outputs.environment }}
        path: |
          target/surefire-reports/
          target/site/
          extent-reports/
    
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          target/surefire-reports/*.xml
    
    - name: Send Slack notification
      if: always()
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        channel: '#automation-${{ steps.env.outputs.environment }}'
        fields: repo,message,commit,author,action,eventName,ref,workflow
        text: |
          Booking Automation Tests Completed
          Environment: ${{ steps.env.outputs.environment }}
          Status: ${{ job.status }}
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  gateway-tests:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/staging'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Run Gateway Tests Only
      run: |
        mvn clean test -Dgroups=gateway -Denvironment=staging
    
    - name: Upload gateway test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: gateway-test-results
        path: |
          target/surefire-reports/
          extent-reports/

  coupon-tests:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/staging'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Run Coupon Tests Only
      run: |
        mvn clean test -Dgroups=coupon -Denvironment=staging
    
    - name: Upload coupon test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: coupon-test-results
        path: |
          target/surefire-reports/
          extent-reports/